version: 2
.conan-steps: &conan-steps
  steps:
    - checkout
    - restore_cache:
        keys:
          - conan-cache
    - run:
        name: Update Conan package
        command: |
          chmod +x .circleci/install.sh
          .circleci/install.sh
    - save_cache:
        key: conan-cache
        paths:
            - ~/Library/Caches/pip
            - ~/Library/Caches/Homebrew
    - run:
        name: Build recipe
        command: |
          chmod +x .circleci/run.sh
          .circleci/run.sh

jobs:
  xcode8:
    macos:
      xcode: "8.3.3"
    environment:
      - CONAN_APPLE_CLANG_VERSIONS: "8.1"
    <<: *conan-steps

  xcode9:
    macos:
      xcode: "9.0"
    environment:
      - CONAN_APPLE_CLANG_VERSIONS: "9.0"
    <<: *conan-steps

workflows:
  version: 2
  build_and_test:
    jobs:
      - xcode8
      - xcode9
